// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuyayUY7b5_8EzxhicGqU5ZjTfW2txdHI',
    appId: '1:775225520018:web:16fd2960a5f233b1c41b4b',
    messagingSenderId: '775225520018',
    projectId: 'mymsg-5cc5d',
    authDomain: 'mymsg-5cc5d.firebaseapp.com',
    storageBucket: 'mymsg-5cc5d.appspot.com',
    measurementId: 'G-8LT3KRT6NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP5XhAKa8LMuYPCt0wc7rvGjVDc3R2flI',
    appId: '1:775225520018:android:870d5871ae0791c0c41b4b',
    messagingSenderId: '775225520018',
    projectId: 'mymsg-5cc5d',
    storageBucket: 'mymsg-5cc5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUt8Y3iQMM7jPLQz353l39P4EnVu_L28Q',
    appId: '1:775225520018:ios:23b0776ef6e1166ac41b4b',
    messagingSenderId: '775225520018',
    projectId: 'mymsg-5cc5d',
    storageBucket: 'mymsg-5cc5d.appspot.com',
    iosBundleId: 'com.example.fluttergroupchatappwithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUt8Y3iQMM7jPLQz353l39P4EnVu_L28Q',
    appId: '1:775225520018:ios:23b0776ef6e1166ac41b4b',
    messagingSenderId: '775225520018',
    projectId: 'mymsg-5cc5d',
    storageBucket: 'mymsg-5cc5d.appspot.com',
    iosBundleId: 'com.example.fluttergroupchatappwithfirebase',
  );
}
